<?php
/**
 * Created by PhpStorm.
 * User: hong
 * Date: 11/8/16
 * Time: 2:28 PM
 */

namespace O\DesignPatterns\Structural\Proxy;


class RecordProxy extends Record
{
    private $isDirty = false;

    private $isInitialized = false;

    public function __construct(array $data)
    {
        parent::__construct($data);

        if (count($data) > 0)
        {
            $this->isDirty = true;
            $this->isInitialized = true;
        }
    }

    public function __set(string $name, string $value)
    {
        $this->isDirty = true;

        parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    public function isDirty(): bool
    {
        return $this->isDirty;
    }
}
